# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a13b2a34afa95482413c7513e7a3c4ee248cee796b02aba84271562b5a020a1488e44d5f308534a9c30f8111ad804648d4d493ba2300e0839b75577e2611d450

test:
  secret_key_base: a8b26d76bf8f75646ce2209cdf8d3caed94455077f52b055341fbcd93d37ddc19c4c51e832b29905e8d3354b53d0dbedde39f5880cf4fbe951471499a82cea56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
